name: Data Product Deploy - preview
on:
  push:
    tags:
      - "preview-v[0-9]+.[0-9]+.[0-9]+-[0-9][0-9][0-9]"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
permissions:
  id-token: write  # Allow the job to request an OIDC token
  contents: read   # Allow the job to read repository contents

jobs:
  generate-and-deploy:
    name: "Data Product Deploy - preview"
    runs-on: ubuntu-latest
    environment: uat # You can't change environment names, so `preview` is called `uat`
    env:
      DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      DATABRICKS_BUNDLE_ENV: ${{ vars.ENVIRONMENT_NAME }}
      DATABRICKS_AUTH_TYPE: "azure-cli"
      PRODUCT_NAME: usage_info
      BUNDLE_VAR_repository: https://github.com/${{ github.repository }}
      BUNDLE_VAR_git_ref_name: https://github.com/${{ github.ref_name }}
    steps:
      - name: Show git information 💡
        run: |
         echo "event_name: ${{ github.event_name }}"
         echo "ref: ${{ github.ref }}"
         echo "ref_type: ${{ github.ref_type }}"
         echo "ref_name: ${{ github.ref_name }}"
      - name: Checkout Repo 💻
        uses: actions/checkout@v4
      # Use the azure/login action to sign in to Azure via workload identity
      - name: 'Az CLI Login'
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          # The azure/login action handles the OIDC token exchange automatically
      - name: Set up Databricks CLI 🧱
        uses: databricks/setup-cli@main
      - name: Set up Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Install pip dependencies 💾
        run: |
          pip install -r requirements.txt
      - name: Block DAB permissions assignment
        run: |
          python scripts/check_no_permissions_in_dab.py
      - name: Convert Data Contract ➡️ Markdown + HTML + ODCS
        run: |
          python scripts/export_contract.py contracts datacontract.odcs.yml ${{ github.ref_name }} $PRODUCT_NAME
      - name: Convert Data Contract ➡️ Unity Catalog Scripts
        run: |
          python scripts/uc_datacontract.py ${{ github.repository }} ${{ github.ref_name }} --template_file contract_to_unitycatalog_template.py --gold_dlt_file_name dlt.gold.py --import_file_name imports.py
      - name: Display directory contents 📂
        run: |
          ls -R 
      - name: Deploy Databricks Bundle 🚀
        run: databricks bundle deploy
        working-directory: .
      - name: Run Pipeline 🏃‍➡️
        run: databricks bundle run deploy_job
        working-directory: .